# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, save-task-localstorage ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm ci
    - run: npm run build
    #- run: npm test
    - name: Commit generated build files
      run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # git add $SCRIPT_OUTPUT_FILE_PATH
          git add dist/*
          # https://stackoverflow.com/a/25149786 for git status --porcelain
          # https://git-scm.com/docs/git-status#Documentation/git-status.txt--ultmodegt to ignore untracked files
          if [[ `git status -uno --porcelain` ]]; then
            git commit -m "Update production distribution on $(date)"
            git push
            echo "Successfully updated production distribution"
          else
            echo "Error updating production distribution"
          fi
